### DISCUSSION TITLE
How can I limit resources for integration containers (in docker and minikube)?

### DISCUSSION THREAD

**Discussion by MyLuk** [apache/camel-karavan#1046] [Q&A] [answered]
Hi team,

I tried limiting resources for a container in docker. I thought that this could be done in the _docker-compose.yaml_ template.

![image](https://github.com/apache/camel-karavan/assets/23213952/6d370268-cb59-4477-9f99-e8c9984c9ee0)

I edited this file, built a new image and deploy the container.

But the dashboard shows that there are no memory limits.

![image](https://github.com/apache/camel-karavan/assets/23213952/6f5b53ff-2baf-4ae3-b49f-0d48f49a62ae)

How can I limit resources for integration containers (in docker and minikube)?

I'm using the 4.3.0 version of camel-karavan

**Comment by mgubaidullin** [comment, marked as answer]
1. In Kubernetes add fragment file `deployment.jkube.yaml` to your project
```
spec:
  containers:
  - resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```
