### DISCUSSION TITLE
Caching a header from one route to another

### DISCUSSION THREAD

**Discussion by samar-elsayed** [apache/camel-karavan#1070] [Q&A]
Hi,

I am trying to cache a certain header **(CamelCaffeineKey)** to use it in another route so I have tried caffeine-cache but I dont seem to be able to make it work, could you please explain to me how to use it / load the cache from the first route to the other route?

![image](https://github.com/apache/camel-karavan/assets/22873802/00cacbd0-7822-4f62-8a39-0b27246d8b92)

**Comment by mgubaidullin** [comment]
@davsclaus is Caffeine Cache component scope is Route or CamelContext?

**Comment by oscerd** [comment]
You can bind the cache to registry and re-use the same instance in multiple routes of the context https://camel.apache.org/components/4.0.x/caffeine-cache-component.html#_examples

**Comment by davsclaus** [comment]
its context scoped (in reality per component), also it creates a default in-memory cache if not specially created as the link from Andrea above.

**Comment by mgubaidullin** [comment]
Thanks @davsclaus and @oscerd 

@samar-elsayed you can not put header directly to Caffeine. Set the data you want to cache to exchange body and then put into caffeine cache. In the second route get data from caffeine (it will be in exchange body) and then setHeader from the body.

```
- route:
    id: route-cbf4
    nodePrefixId: route-1f7
    from:
      id: from-7856
      uri: kamelet:timer-source
      parameters:
        message: Hello
      steps:
        - setBody:
            id: setBody-eaa0
            expression:
              simple:
                id: simple-3dc1
                expression: ${date:now}
        - to:
            id: to-604c
            uri: caffeine-cache
            parameters:
              cacheName: demo1
              action: PUT
              key: key1
- route:
    id: route-778e
    nodePrefixId: route-289
    from:
      id: from-aedc
      uri: kamelet:timer-source
      parameters:
        message: world
      steps:
        - to:
            id: to-191e
            uri: caffeine-cache
            parameters:
              cacheName: demo1
              action: GET
              key: key1
        - log:
            id: log-d474
            message: ${body}
```
