### DISCUSSION TITLE
Extend the pod specs for the dev mode and build

### DISCUSSION THREAD

**Discussion by arheom** [apache/camel-karavan#1107] [Q&A] [answered]
Is there a way we could extend / customize the pod / deployment yaml file of the run in devmode and build? Basically, we need to push some traits / tolerances to the pods running, and could not find a way to update it.

Thanks!

**Comment by mgubaidullin** [comment, marked as answer]
Add `deployment.jkube.yaml` to your project with deployment spec fragment, ex:
```
spec:
  replicas: 1
  template:
    spec:
      containers:
        - volumeMounts:
            - name: xxx
              mountPath: /xxxxx
      serviceAccount: karavan
      imagePullSecrets:
        - name: karavan-registry
```

works for build, not for devmode

**Reply by arheom** [reply]
Thanks for the info! I assume this is for the deployment right? Not for builder? Could we also add some specs to the builder as well? Basically, we have multiple nodes on arm, and one on amd. And, unfortunately, the karavan image does not work on arm (on eks), so we have a taint and a node selector to move the workload to the amd node. Which I managed to do, but when using karavan web app, and clicking the build button, the pod is scheduled by default on arm, which fails to work, so I try to imagine how we can also modify the builder specs, to schedule to the amd node. 

Thanks!

**Reply by mgubaidullin** [reply]
Yes this is for deployment.

Builder. Correct me if I am wrong but if image is multi-arch than it will work on k8s on arm? If this is the case than we just need to build multi-arch images for karavan web-app and builder

**Reply by arheom** [reply]
yes, if the manifests for both architectures are there, then the proper image arch is pulled depending on the k8s cluster settings. I can make a PR this week with the changes to support multi-arch image publishing. Apart from amd64 and arm64, would any other architecture be interesting to be supported?

**Comment by mgubaidullin** [comment]
`Traits are high level named features of Camel K` Karavan does not use Camel-K but Camel+Jib+JKube

**Reply by arheom** [reply]
Sorry, now I read I mistyped it. I meant taints and not traits. Basically, as explained in the reply above, we tainted some kubernetes nodes with arm and amd, so the workload which cannot work on arm, is scheduled to the amd node. But in order to make it work, I need to push some specs to all pods generated by karavan. Something like:
```
spec:
      nodeSelector:
        kubernetes.io/arch: amd64
      tolerations:
      - operator: "Exists"
```
