### DISCUSSION TITLE
Reusing kamelet multiple times in same route

### DISCUSSION THREAD

**Discussion by enter-marlah** [apache/camel-karavan#1233] [Q&A] [answered]
### Ask a question

I have created a kamelet that writes a custom log message with log action.

When I try to use the Kamelet more than once in a route, I get an error saying that the id of the log action in the kamelet is not unique. The error is: Failed to start route X because of duplicate id detected: Y. Please correct ids to be unique among all your routes.

What I am doing wrong? Karavan sets the id for the action. Is it possible to make it dynamic or what could I try?

Thanks!

### Variant

Web Application

### Container Management (if applicable)

Kubernetes

### Operating System (if applicable)

Linux

### Version

4.4.0

**Comment by davsclaus** [comment]
Can you show your custom kamelet code

**Reply by enter-marlah** [reply]
The duplicate error comes from the setvariable step

```
apiVersion: camel.apache.org/v1
kind: Kamelet
metadata:
  name: custom-log-action
  annotations:
    camel.apache.org/kamelet.support.level: Preview
    camel.apache.org/catalog.version: "1"
    camel.apache.org/provider: test
    camel.apache.org/kamelet.group: test
    camel.apache.org/kamelet.namespace: test
  labels:
    camel.apache.org/kamelet.type: action
spec:
  definition:
    title: custom-log-action
    description: Writes log with extra parameters
    required:
      - property0
      - property1
      - property2
    type: object
    properties:
      property3:
        title: TargetID
        description: Target Desc
        type: string
        default: "-"
      property0:
        title: message
        description: Actual log message
        type: string
        enum: []
      property1:
        title: event_type
        description: Event type desc
        type: string
        example: INFO,DEBUG,ERROR,WARNING
      property2:
        title: event_id
        description: Event type id
        type: number
  types:
    in:
      mediaType: ""
    out:
      mediaType: ""
  template:
    route:
      id: route-fa82
      from:
        id: from-688a
        uri: kamelet:source
        steps:
          - setVariable:
              id: setVariable-00c6
              name: logjson
              expression:
                java:
                  id: java-3e75
                  expression: >
                    return "{\"event_message\":
                    \"{{property0}}\",\"event_type\":
                    \"{{property1}}\",\"event_id\":
                    \"{{property2}}\",\"event_target_id\": \"{{property3}}\"}';
          - log:
              id: log-ffe5
              message: ${variable.logjson}
```

**Reply by davsclaus** [reply, marked as answer]
Ah okay, you should remove those id's

You can also add nodePrefixId to the `route` and have it exposes as a property to the kamelet, where you can then specify some unique id.

But ideally we should find a way to make kamelets use unique ids automatic so you wont have this problem anymore at all.
https://issues.apache.org/jira/browse/CAMEL-20687

**Reply by enter-marlah** [reply]
Thanks, for the reply but I cant remove those Id's since Karavan always adds them back automatically. I will try the nodePrefix.

**Comment by enter-marlah** [comment]
Can you give me an example how to use the nodePrefix? When I try to use it, every time I put something in the field and leave the page the field goes blank. Thanks!

**Reply by davsclaus** [reply]
Okay could be a bug in karavan, you can try the new 4.5.0 release.
And in Camel 4.6 onwards then your kamelets would work out of the box.

**Reply by enter-marlah** [reply]
Ok, I will try the 4.5.0 karavan.

I also tried the following. I have a route with two of those custom kamelets. I set parameter for both kamelets and made that parameter part of the id field so I could get unique ids. The problem with this was that both kamelets have the parameter value from the first kamelet even I had set different values for both kamelets in my route. 

How can I reinitialize the second kamelet with fresh values?

here is a part of my route:
```
        - to:
            id: to-bea8
            uri: kamelet:rv-log-action
            parameters:
              property3: target1
              property0: message1
              property1: INFO
              property2: 123
              setVariableId: id1
        - to:
            id: to-8822
            uri: kamelet:rv-log-action
            parameters:
              property3: target2
              property0: message2
              property1: INFO
              property2: 456
              setVariableId: id2
```

And here is how I set them in the kamelet:

```
template:
    route:
      id: route-ccbc
      from:
        id: from-688a
        uri: kamelet:source
        steps:
          - setVariable:
              id: "{{setVariableId}}"
```

And the error from this is Failed to create route X from template Y because of duplicate id detected: id1. Please correct ids to be unique among all your routes.
