### DISCUSSION TITLE
Use a component as consumer but with 'direct' endpoint

### DISCUSSION THREAD

**Discussion by cdia8890** [apache/camel-karavan#1310] [Q&A] [answered]
### Ask a question

I have a route that reads a file from a given location. I need to invoke this route from another route using `direct` endpoint. 
But when I define the routes like below, the `file` component is acting as a writer (with `to`) but not as a reader.

```
file-service.yaml
- route:
    id: route-487d
    nodePrefixId: route-d0d
    from:
      id: from-effa
      uri: timer
      parameters:
        timerName: test-timer
        repeatCount: "1"
      steps:
        - to:
            id: to-1db5
            uri: direct
            parameters:
              name: read-from-file
```

```
- route:
    id: file-reader
    nodePrefixId: route-d8c
    from:
      id: from-568a
      description: read-from-file
      uri: direct
      parameters:
        name: read-from-file
      steps:
        - setHeader:
            id: setHeader-eae6
            name: CamelFileName
            expression:
              simple:
                id: simple-2b61
                expression: dummy-sftp-file.txt
        - log:
            id: log-ec3b
            message: reading from file - ${headers.CamelFileName}
        - to:
            id: from-6930
            uri: file
            parameters:
              directoryName: "{{sys:user.dir}}/temp_files"
              fileName: ${headers.CamelFileName}
              autoCreate: false
        - to:
            id: to-5a41
            uri: log
            parameters:
              loggerName: file-processor-logger
              showAll: true
              showAllProperties: true
              showFiles: true
              showHeaders: true
              showVariables: true
```

Since the file reader is using `to` directive, I assume Camel is interpreting that as a producer. And as I know we cannot use two `from` directives. How to accomplish the file reader while still using `direct` endpoint? 

P.S: I found about the `PollEnrich` but that requires hard coding the `file` endpoint within the PollEnrich component. I need to have the `file-reader` route separately and invoke from another route.

### Variant

Vs Code Extension

### Container Management (if applicable)

None

### Operating System (if applicable)

Windows

### Version

4.5.0

**Comment by davsclaus** [comment]
Using `to:file` is for writing a file (not reading). To read you need to either use `from:file` or use `pollEnrich:file`.

**Reply by cdia8890** [reply]
is there an option to use pollEnrich with `routeId`? Like define the file reader route with `direct` and use that in the pollEnrich option?

**Reply by davsclaus** [reply]
I dont understand what you ask

**Reply by cdia8890** [reply]
Something like this. Basically to externalize the file reader logic and invoke it from another route ad-hoc. 

Like imagine that I have a Java code running some logic and in the middle read a file from a given location.

```
file-reader.yaml
- route:
    id: route-5ea9
    nodePrefixId: route-bdd
    from:
      id: from-2d29
      uri: file
      parameters:
        directoryName: test
```

```
- route:
    id: file-reader
    nodePrefixId: route-d8c
    from:
      id: from-568a
      description: read-from-file
      uri: direct
      parameters:
        name: read-from-file
      steps:
        - setHeader:
            id: setHeader-eae6
            name: CamelFileName
            expression:
              simple:
                id: simple-2b61
                expression: dummy-sftp-file.txt
        - log:
            id: log-ec3b
            message: reading from file - ${headers.CamelFileName}
        - pollEnrich:
            id: pollEnrich-3f9e
            uri:
              routeId: route-5ea9 <------------------------------ call file-reader route from pollEnrich.
```
