### DISCUSSION TITLE
what is package of uploaded java class

### DISCUSSION THREAD

**Discussion by git-josip** [apache/camel-karavan#1330] [Q&A] [answered]
### Ask a question

When I upload example. 

Kafka custom partitioner: 

```
import org.apache.kafka.clients.producer.Partitioner;
import org.apache.kafka.common.Cluster;

import java.util.Map;

public class ByKeyPartitioner implements Partitioner {

    @Override
    public int partition(String topic, Object key, byte[] keyBytes, Object value, byte[] valueBytes, Cluster cluster) {
        int partitionKeyAsString = (String) key;
        Integer keyInt = new Integer(partitionKeyAsString);
        return keyInt % 20;
    }

    @Override
    public void close() {

    }

    @Override
    public void configure(Map<String, ?> configs) {

    }
}
```

what is package of this class?

Ass I need to reference it in camel kafka component by class. 

![Screenshot 2024-06-27 at 19 10 39](https://github.com/apache/camel-karavan/assets/807887/35977633-f9b0-4909-ae1d-d0b49d3c4950)

I tried many different approaches but I can not get it work, I am getting error there is no class. 
`org.apache.kafka.common.config.ConfigException: Invalid value ByKeyPartitioner for configuration partitioner.class: Class ByKeyPartitioner could not be found` 

What is the package of upldoaded file, as I need to provide it obviously ? 

### Variant

None

### Container Management (if applicable)

None

### Operating System (if applicable)

None

### Version

None

**Comment by mgubaidullin** [comment]
I believe that package should be related to your `camel.jbang.gav` property in `application.properties`

**Comment by davsclaus** [comment]
this code is wrong
```
  int partitionKeyAsString = (String) key;
```

/ByKeyPartitioner.java:10: error: incompatible types: java.lang.String cannot be converted to int
        int partitionKeyAsString = (String) key;

**Comment by davsclaus** [comment]
This can run

Put in `application.properties`

```
camel.jbang.dependencies=camel-kafka
```

And fix that compilation error in your java code

Here is yaml-dsl that runs for me
```
- route:
    id: route-2842
    nodePrefixId: route-05e
    from:
      id: from-71ad
      uri: timer
      parameters:
        timerName: trigger
      steps:
        - to:
            id: to-9242
            uri: kafka
            parameters:
              topic: cheese
              partitioner: ByKeyPartitioner
              brokers: localhost:1234
```
