### DISCUSSION TITLE
Decorating devpod and builder pod with security context in kubernetes?

### DISCUSSION THREAD

**Discussion by arheom** [apache/camel-karavan#1364] [Q&A]
### Ask a question

In order to run Karavan inside our environment, we need to pass some security policies. Some of them, need some changes inside the pod / deployment files. Is there any way I can make those changes (under securityContext) for the builder pod and demo / dev pod? For the actual project, I know, I can use the jkube files to ensure the settings, but not sure about the builder and the dev run ones?

### Variant

Web Application

### Container Management (if applicable)

Kubernetes

### Operating System (if applicable)

MacOS

### Version

4.7.0

**Comment by mgubaidullin** [comment]
`Resources` menu -> `configuration` project -> `builder.pod.jkube.yaml`
Set securityContext and it should apply to DevMode and builder

**Reply by schoettkert** [reply]
I tried this solution, but i assume securityContext on container level is overwritten by `KubernetesService`:

```
Container container = new ContainerBuilder()
                .withName(name)
                .withImage(projectDevmodeImage != null ? projectDevmodeImage : devmodeImage)
                .withPorts(port)
                .withResources(resources)
                .withImagePullPolicy(devmodeImagePullPolicy.orElse("IfNotPresent"))
                .withEnv(new EnvVarBuilder().withName(ENV_VAR_JBANG_OPTIONS).withValue(jbangOptions).build())
                .withVolumeMounts(volumeMounts)
                .build();
```

```
spec:
  replicas: 1
  template:
    spec:
      securityContext:
        runAsUser: 1000
        runAsNonRoot: true
        runAsGroup: 1000
      containers:
        - securityContext:
          runAsUser: 1000
          runAsNonRoot: true
          runAsGroup: 1000
          capabilities:
            add:
              - CHOWN
            drop:
              - ALL
```

So my changes for capabilities to `deployment.jkube.yaml` are not transferred to the resulting deployment.

Which results in this error:
require-drop-all: 'validation failure: Containers must drop `ALL` capabilities.'

Is this correct?
