### DISCUSSION TITLE
How can i add Maven plugin for camel-salesforce component on karavan?

### DISCUSSION THREAD

**Discussion by thanhloc1993** [apache/camel-karavan#1367] [Q&A] [answered]
### Ask a question

How can i add Maven plugin for camel-salesforce component on karavan?
https://github.com/apache/camel/tree/main/components/camel-salesforce/camel-salesforce-maven-plugin

Context:
```
  id: to-6466
            uri: salesforce
            parameters:
              operationName: query
              sObjectQuery: >-
                select
                Id,Name,ABC
                FROM XYZ__c  
              lazyStartProducer: false
              sObjectClass: I must set this
```

### Variant

None

### Container Management (if applicable)

None

### Operating System (if applicable)

None

### Version

None
