### DISCUSSION TITLE
How to mount volume to pod in kubernetes

### DISCUSSION THREAD

**Discussion by tannextan** [apache/camel-karavan#1426] [Q&A] [answered]
### Describe the bug

Trying to change deployment.jkube.yaml to add nfs volume, but Karavan when deploy the pod doesnot have the volumeMount i am adding in the jkube.yaml. What is the work around for it? 

### Steps to reproduce the behavior

1. Go to '...'a

### Variant

Web Application

### Container Management (if applicable)

Openshift

### Operating System (if applicable)

Linux

### Version

4.7.0

**Comment by mgubaidullin** [comment]
I tried to reproduce your issue using **Steps to reproduce the behavior** you provided and I could not

**Comment by tannextan** [comment]
Then please tell me how can i attach a volume in project pod created by
karavan ? please give an example

**Comment by mueckinger** [comment, marked as answer]
This works:
```yaml
spec:
  replicas: 1
  template:
    spec:
      serviceAccount: karavan
      containers:
        - volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          hostPath: 
            path: /data/karavan
```
