### DISCUSSION TITLE
karavan 4.8.0  bug never  open second port why?

### DISCUSSION THREAD

**Discussion by nturri1306** [apache/camel-karavan#1435] [General]
//port 7080 always remains closed ignores it even if I change my number

//hello this is my docker compose

```
services:
  mllptest:
    image: mllptest
    restart: always
    ports:
      - "8081:8080"
      - "7080:7080"
      
    networks:
      - karavan
```

//project

```
- route:
    id: route-328c
    nodePrefixId: route-264
    from:
      id: from-f6f9
      uri: mllp
      parameters:
        hostname: 0.0.0.0
        port: "7080"
        validatePayload: true
      steps:
        - process:
            id: process-df54
            ref: myProcessor


```
//code processor

```
import org.apache.camel.BindToRegistry;
import org.apache.camel.Configuration;
import org.apache.camel.Exchange;
import org.apache.camel.Processor;

@Configuration
@BindToRegistry("myProcessor")
public class myProcessor implements Processor {

    public void process(Exchange exchange) throws Exception {
   
        System.out.println(exchange.getIn().getBody(String.class));
    }
}


```
