### DISCUSSION TITLE
How do I activate the trace on karavan ide?

### DISCUSSION THREAD

**Discussion by nturri1306** [apache/camel-karavan#1438] [Q&A] [answered]
How do I activate the trace on karavan ide?

![image](https://github.com/user-attachments/assets/a9301d57-3cd3-405f-a1bb-958e12256dd5)

```
- rest:
    id: rest-ce43
    put:
      - id: put-7609
        path: upload
        to: direct:upload
- route:
    id: upload
    from:
      id: from-e73e
      uri: direct
      parameters:
        name: upload
      steps:
        - unmarshal:
            id: unmarshal-9f29
            json:
              id: json-d4dc
        - split:
            id: split-99e2
            expression:
              simple:
                id: simple-765a
                expression: ${body}
            steps:
              - to:
                  id: to-8f74
                  uri: kamelet:log-action
                  parameters:
                    multiline: true
                    level: TRACE
        - setBody:
            id: setBody-2bc9
            expression:
              constant:
                id: constant-fb43
                expression: ok
```

**Comment by mgubaidullin** [comment]
I believe that is should be `camel.trace.enabled=true` set to activate traces

**Comment by nturri1306** [comment]
i ve insert the tracing true but not have result

![image](https://github.com/user-attachments/assets/ccc83c6c-985a-4e59-ac23-26aa67a12bf9)


`--- [           main] org.apache.camel.main.BaseMainSupport    :     [log-action.kamelet.yaml]      level = TRACE`

```
- camel:
  main:
    tracing: true

- rest:
    id: rest-ce43
    put:
      - id: put-7609
        path: upload
        to: direct:upload
- route:
    id: upload
    from:
      id: from-e73e
      uri: direct
      parameters:
        name: upload
      steps:
        - unmarshal:
            id: unmarshal-9f29
            json:
              id: json-d4dc
        - split:
            id: split-99e2
            expression:
              simple:
                id: simple-765a
                expression: ${body}
            steps:
              - to:
                  id: to-8f74
                  uri: kamelet:log-action
                  parameters:
                    multiline: true
                    level: TRACE
        - setBody:
            id: setBody-2bc9
            expression:
              constant:
                id: constant-fb43
                expression: ok
```
