### DISCUSSION TITLE
Build vs. dev mode difference

### DISCUSSION THREAD

**Discussion by filojalo** [apache/camel-karavan#1451] [Q&A] [answered]
### Ask a question

Hi, I am testing out a simple integration that would run the built image in k8s and use config map syntax from https://camel.apache.org/manual/using-propertyplaceholder.html to reference them.

Integration:
```
- rest:
    id: rest-d471
    post:
      - id: post-126a
        path: /variableInjection
        to: direct:injectionTest
- route:
    id: route-a292
    from:
      id: from-b12a
      uri: direct
      parameters:
        name: injectionTest
      steps:
        - log:
            id: log-f62e
            message: >-
              Printing test variable
              {{configmap:camel-configmap/test_variable:default}}
```

application.properties include
```
camel.kubernetes-config.mount-path-configmaps=/etc/camel/myconfig/
camel.kubernetes-config.client-enabled=false
```

Now when running it in devmode it correctly returns the default (since there is no config map)
![image](https://github.com/user-attachments/assets/55f3d18c-f37c-4680-9dcb-8c675059ddf9)

When building the image and running it on Minikube on my local
![image](https://github.com/user-attachments/assets/17ea242d-4d2d-4b8e-84e4-a31bcede8ef9)

I am using the default build.sh script
What is the difference? Why doesnt the built image output the default?

### Variant

Web Application

### Container Management (if applicable)

Docker

### Operating System (if applicable)

Linux

### Version

4.8.0
