### DISCUSSION TITLE
csv component

### DISCUSSION THREAD

**Discussion by laiyuanliu** [apache/camel-karavan#788] [Q&A] [answered]
Hi, I'm new to Karavan.

I'm trying to build a flow using Karavan to parse some CSV file. but I cannot find the CSV component when I use Karavan in VS code. the CSV component is part of the camel component catalog since version 1.3.

can you please help me understand what I'm missing?

Thanks in advance

**Comment by davsclaus** [comment]
CSV is part of dataformats, so you can use marshal or unmarshal in EIPs and then select CSV as the data format

**Comment by davsclaus** [comment, marked as answer]
You can try http://karavan.space to build a route, such as

```
- route:
    id: route-40dd
    from:
      uri: file:inbox
      id: from-6f9a
      steps:
        - marshal:
            id: marshal-00d6
            csv:
              id: csv-a750
        - split:
            id: split-89c3
            expression:
              simple:
                expression: ${body}
                id: simple-c0f3
            steps:
              - to:
                  uri: jms:line
                  id: to-c84e
```
