### DISCUSSION TITLE
[Question] Exchange Pattern config

### DISCUSSION THREAD

**Discussion by hguerrero** [apache/camel-karavan#793] [Q&A] [answered]
Where can we configure the `exchangePattern`, for example, if I want to use it for `InOnly` in my JMS routes?

**Comment by mgubaidullin** [comment]
I believe it is something like that:

<img width="1210" alt="Screenshot 2023-06-13 at 5 57 28 PM" src="https://github.com/apache/camel-karavan/assets/1379213/add27887-558b-4960-afc3-0905cac02960">

**Reply by hguerrero** [reply]
My issue is that I need to change the exchange pattern only for one step rather than the complete route. My route is an HTTP endpoint that sends a fire-and-forget message to a JMS topic. Still, the HTTP call needs to send back a response.

**Reply by mgubaidullin** [reply]
Something like that should work:
```
- rest:
    id: rest-f1bf
    post:
      - id: post-1860
        to: direct:derect1
- route:
    id: derect1
    from:
      uri: direct:derect1
      id: from-51ad
      steps:
        - to:
            uri: kamelet:jms-apache-artemis-sink
            id: to-d48b
            parameters:
              destinationType: queue
              destinationName: queue1
              brokerURL: tcp://my-host:61616
        - setBody:
            id: setBody-ec18
            expression:
              constant:
                expression: RESPONSE
                id: constant-99fa
```
