### DISCUSSION TITLE
Karavan as a documentation tool

### DISCUSSION THREAD

**Discussion by ck1125** [apache/camel-karavan#966] [Q&A] [answered]
Thanks for such a fantastic product, folks.

I would love to operationalise the use Karavan's route design features as a way to visually document my integration flow and don't know how to go about it. Within VsCode it doesn't always recognise and draw out yaml files that I throw at it. Does anyone have suggestions for how this can be achieved?

Cheers

**Comment by davsclaus** [comment]
Do you have examples of YAML that it cannot draw?

**Reply by ck1125** [reply]
It can draw but seems to require modifications to the yaml. I'm not sure if this is because of version discrepancies with regards Karavan's supported Camel version (4.x) and older versions (3.14.x).  For example even after I rollback to the plugin version I find that the following yaml fails to render properly. The extension settings version doesn't seem to help 

```
- route: 
      id: a-route-id
      from: 
         uri: direct:some-route-uri
      steps:
          - bean:
                 ref: a-bean-ref
                 method: aMethod
```

I find that I need to  change it to the following for things to render properly:

```
- route: 
      id: a-route-id
      from: 
         uri: direct:some-route-uri
         steps:
            - bean:
                   ref: a-bean-ref
                   method: aMethod
```

My original question though about a path to being able to use this awesome tool to visually document my routes for others (a non-technical audience) without having to launch VsCode (either via an exported image) or from a web UI would be helpful to get some pointers to 🙏🏽
