### ISSUE TITLE
doTry .. doCatch seems to not render the arraw from doTry to the next EIP

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#1017]
See this screenshot, from the following yaml

```
- route:
    nodePrefixId: route-bd7
    id: route-60b0
    from:
      uri: kamelet:aws-ddb-streams-source
      id: from-8c66
      steps:
        - doTry:
            id: doTry-9c0c
            doCatch:
              - onWhen:
                  when:
                    expression:
                      simple:
                        expression: aaaaa
                        id: simple-f7ce
                    id: when-a03c
                id: doCatch-5aef
                steps:
                  - log:
                      message: ${body}
                      id: log-2769
            steps:
              - process:
                  id: process-0740
        - bean:
            id: bean-9696
        - process:
            id: process-ba12
```
