### ISSUE TITLE
Designer with filter does not have arrow to next EIP

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#1018]
```
- route:
    nodePrefixId: route-980
    id: route-1436
    from:
      uri: kamelet:aws-kinesis-source
      id: from-70a1
      steps:
        - filter:
            expression:
              simple:
                id: simple-9d72
            id: filter-0af7
            steps:
              - enrich:
                  expression:
                    simple:
                      id: simple-0fe3
                  id: enrich-633f
        - removeProperty:
            id: removeProperty-f586
        - pausable:
            id: pausable-54a1
        - process:
            id: process-2bf5
```
