### ISSUE TITLE
Karavan on minikube on macos does not start

### ISSUE THREAD

**Issue by arheom** [apache/camel-karavan#1096]
As context, I have a macOS with arm, and I try to install the latest karavan (4.3.0) on a minikube on it. 

I followed the instructions from github, and also including with colima and it does not work. I managed to make it working with colima on docker, but not on minikube.

All pods start, except the karavan one, with the error: 

> exec /__cacert_entrypoint.sh: exec format error

which I understood comes from the fact it tries to run on arm.

Anyone experimented with minikube on macos? Do you have any hint to try it out?

Thanks!

**Comment by arheom** [comment]
Thats great to know it works on macos (I have M1). Do you have any suggestion what to try? I used this guide here: https://github.com/apache/camel-karavan/blob/main/docs/WEB_KUBERNETES.md

with some exceptions, like I could not install hyperkit:

> hyperkit: The x86_64 architecture is required for this software.
> Error: hyperkit: An unsatisfied requirement failed this build.

Thanks!

**Comment by mgubaidullin** [comment]
I used minikube with docker driver https://minikube.sigs.k8s.io/docs/drivers/docker/

**Comment by arheom** [comment]
From what I understood, in order to work on multi arch, the image needs to support it. When I try to get the correct image for my platform:

```
docker pull --platform linux/arm64 ghcr.io/apache/camel-karavan:4.3.1
4.3.1: Pulling from apache/camel-karavan
Digest: sha256:a17e537d15969a95d4bbb970d2b312ae8dd9a5017c9c89349d68906e4a805cee
Status: Image is up to date for ghcr.io/apache/camel-karavan:4.3.1
image with reference ghcr.io/apache/camel-karavan:4.3.1 was found but does not match the specified platform: wanted linux/arm64, actual: linux/amd64
```
Getting the amd64 image.

From what I understood, here: https://cloud.google.com/kubernetes-engine/docs/how-to/build-multi-arch-for-arm
we could support both architectures with buildx and it will append the 2 manifests, so we can pull the proper one, based on our environment.

Maybe could you point me in the right direction where this happens into the code, maybe I could make a PR to build the image in both arch if not already done?

**Comment by arheom** [comment]
I forked the repo, to be able to easily test the flows and I managed to publish the devmode image with multi platform architecture and I could test it that it works well. I changed the code to this:

```
jobs:
  docker:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./karavan-web/docker
          platforms: linux/amd64,linux/arm64
          file: karavan-web/docker/Dockerfile.devmode
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ env.TAG }}
```
