### ISSUE TITLE
Extend the pod specs for the dev mode and build

### ISSUE THREAD

**Issue by arheom** [apache/camel-karavan#1106]
Is there a way we could extend / customize the pod / deployment yaml file of the run in devmode and build? Basically, we need to push some traits / tolerances to the pods running, and could not find a way to update it.

Thanks!

**Comment by mgubaidullin** [comment]
Add `deployment.jkube.yaml` to your project with deployment spec fragment, ex:
```
spec:
  replicas: 1
  template:
    spec:
      containers:
        - volumeMounts:
            - name: xxx
              mountPath: /xxxxx
      serviceAccount: karavan
      imagePullSecrets:
        - name: karavan-registry
```

works for build, not for devmode
