### ISSUE TITLE
vscode: Respect .gitignore when scanning for kamlets

### ISSUE THREAD

**Issue by drmaniac** [apache/camel-karavan#1151]
![image](https://github.com/apache/camel-karavan/assets/3472747/b1840328-e088-4f52-aa8a-26f07e3ed44a)

When I use karavan within a project, it also scans folders that are specified in the .gitignore file. This results in files being displayed multiple times in the integration view.

Perhaps it would also be good to specify the folders to be searched in the vscode settings.
Or to have a .karavan settings file.

This could then look like this, for example.

``` yaml
integrations:
  exclude:
    - bin
    - build
  include:
    - **//resources/routes
openapi:
  exclude: bin
  include: **//resources/openapi
```
