### ISSUE TITLE
Karavan Space - List of suggested variables includes Undefined

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#1161]
Copy this example yaml into karavan.space, and click the dropdown for list of existing variables. Notice the last says Undefined.

```
- route:
    id: route-fc08
    from:
      id: from-4fb2
      uri: timer
      parameters:
        period: '5000'
        timerName: beers
      steps:
        - to:
            id: to-2b12
            variableReceive: beer1
            uri: https
            parameters:
              httpUri: random-data-api.com/api/v2/beers
        - to:
            id: to-cd9b
            variableSend: undefined
            variableReceive: beer2
            uri: https
            parameters:
              httpUri: random-data-api.com/api/v2/beers
        - setVariable:
            id: setVariable-439c
            name: alc1
            expression:
              jq:
                id: jq-c893
                expression: .alcohol | rtrimstr("%")
                source: beer1
                resultType: float
        - setVariable:
            id: setVariable-14bc
            name: alc2
            expression:
              jq:
                id: jq-73b5
                expression: .alcohol | rtrimstr("%")
                source: beer2
                resultType: float
        - choice:
            id: choice-3fc5
            when:
              - id: choice
                expression:
                  simple:
                    id: simple-699c
                    expression: ${variable.alc1} > ${variable.alc2}
                steps:
                  - log:
                      id: log-6ecf
                      message: >-
                        Beer battle: ${jq(variable:beer1,.name)}
                        (${variable.alc1}%) is stronger than
                        ${jq(variable:beer2,.name)} (${variable.alc2}%)
            otherwise:
              id: otherwise-03ac
              steps:
                - log:
                    id: log-2477
                    message: >-
                      Beer battle: ${jq(variable:beer1,.name)}
                      (${variable.alc1}%) is weaker than
                      ${jq(variable:beer2,.name)} (${variable.alc2}%)
```
<img width="1557" alt="Screenshot 2024-03-04 at 21 09 29" src="https://github.com/apache/camel-karavan/assets/477100/aea0ecd2-bda1-498e-b692-28c6089959b7">
