### ISSUE TITLE
Defining beans in Karavan creates a bit of verbose yaml output

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#1232]
### Describe the solution you'd like

Using karava.space to create a bean that just has a name, and a class, then outputs

```
- registryBean:
    constructors: {}
    properties: {}
    beans:
      - constructors: {}
        name: foo
        type: com.foo.MyProcessor
```

The `constructors` and  `properties` under `-registryBean` seems like a bug.
And since the `foo` bean has no constructors, then it would be nicer to omit the empty map.

### Variant

Web Application

### Container Management (if applicable)

None
