### ISSUE TITLE
Enricher component breaks UI builder

### ISSUE THREAD

**Issue by dpalinic** [apache/camel-karavan#1237]
### Describe the bug

If we add Enricher component anywhere in our integration, it's impossible to use UI builder for that integration anymore as it leads to blank page.

### Steps to reproduce the behavior

1. Create a new integration
2. Add starting point, e.g. timer or scheduler
3. Add Enricher component
4. Navigate back to Files
5. Try to open same integration file again
6. Observer blank page is opened now instead of integration

Integration sample attached.
[rest-endpoint-enricher.camel.yaml.zip](https://github.com/apache/camel-karavan/files/15025193/rest-endpoint-enricher.camel.yaml.zip)

### Variant

Web Application

### Container Management (if applicable)

None

### Operating System (if applicable)

None

### Version

4.4.0

**Comment by dpalinic** [comment]
Thanks for your quick fix @mgubaidullin . I've tested it and UI is not breaking anymore, but I see that enrich component is returning "404 not found" for any provided endpoint. Am I missing something? Attached integration can be used for testing it as well. It should enrich data as provided url is valid and can be fetched from the browser.

**Comment by mgubaidullin** [comment]
I don't think the Enricher problem is in Karavan. Please Open an issue for Camel: https://issues.apache.org/jira/projects/CAMEL
 
As a workaround you could use HTTP Component:

```
- route:
    id: route-e393
    nodePrefixId: route-754
    from:
      id: from-dc70
      uri: timer
      parameters:
        repeatCount: '1'
        timerName: enricherTimer
      steps:
        - setBody:
            id: setBody-a694
            expression:
              constant:
                id: constant-92a2
                expression: |-
                  1
                  2
                  3
        - split:
            id: split-d7f4
            expression:
              tokenize:
                id: tokenize-c3f2
                token: \n
            steps:
              - setHeader:
                  id: setHeader-13a1
                  name: CamelHttpUri
                  expression:
                    simple:
                      id: simple-306e
                      expression: https://dummyjson.com/products/${body}
              - to:
                  id: to-cd18
                  uri: https
                  parameters:
                    httpUri: https://localhost
                    httpMethod: GET
                    followRedirects: true
              - log:
                  id: log-8287
                  message: ${body}
```

**Comment by mgubaidullin** [comment]
Interesting.... `pollEnrich` works in your case 

@davsclaus should `enrich` work to get data from http?
According to this it should https://camel.apache.org/components/4.4.x/eips/content-enricher.html#_content_enrichment_using_enrich_eip

**Comment by dpalinic** [comment]
It looks like that enrich component is trying to POST a http call instead of using a GET as per default. That could be the reason for a 404. If I provide a header specifying a http method, then enrich works well:

```
              - setHeader:
                  id: setHeader-84d0
                  name: CamelHttpMethod
                  expression:
                    constant:
                      id: constant-6e78
                      expression: GET
```
