### ISSUE TITLE
Key/Value properties style for beans does not work

### ISSUE THREAD

**Issue by mgubaidullin** [apache/camel-karavan#1239]
### Describe the bug

  Karavan supports traditional Bean properties
  
  ```
  template:
    beans:
      - name: dsBean
        type: "#class:org.apache.commons.dbcp2.BasicDataSource"
        properties:
          username: '{{username}}'
          password: '{{password}}'
          url: 'jdbc:postgresql://{{serverName}}:{{serverPort}}/{{databaseName}}'
          driverClassName: 'org.postgresql.Driver'
```
However some Kamelets contains new one

```
  template:
    beans:
      - name: schemaResolver
        type: "#class:org.apache.camel.component.jackson.avro.transform.AvroSchemaResolver"
        property:
          - key: validate
            value: '{{validate}}'
          - key: schema
            value: '{{schema:}}'
```

### Steps to reproduce the behavior

1. Go to '...'a

### Variant

Web Application

### Container Management (if applicable)

None

### Operating System (if applicable)

None

### Version

4.5.0
