### ISSUE TITLE
Jbang Export Not being able to get a key value from application.properties file

### ISSUE THREAD

**Issue by samar-elsayed** [apache/camel-karavan#1343]
### Describe the bug

When I tried to use the value of a key from my application.properties as a Http Uri as shown below :

![image](https://github.com/user-attachments/assets/c6f992c9-d2ab-4d88-afc3-c6c0301fefbe)

I was able to run successfully my integration with Jbang Run but when I tried to do Jbang Export, it failed with `Property with key [Needed_API] not found in properties)`

### Steps to reproduce the behavior

as explained in the description

### Variant

Vs Code Extension

### Container Management (if applicable)

None

### Operating System (if applicable)

Windows

### Version

4.6.0

**Comment by samar-elsayed** [comment]
it seems to also happen in 4.7.0

**Comment by mgubaidullin** [comment]
I believe the issue here is an underscore `_`
Please use `foo.bar.myProperty` systanx

**Comment by samar-elsayed** [comment]
@mgubaidullin I tried that but then I found the https component is getting the value of the property and appending the rest path to it which then gives me a 404 error

example:
rest component (path: /api/v1 ) > direct component > https component (URI: {{Needed.API}}))

what happens is that the call is made to **{{Needed.API}}/api/v1** (it is irrelevant but I have enabled and disabled Bridge Endpoint and the same issue still happens )

**Comment by samar-elsayed** [comment]
@mgubaidullin still hapening 

![image](https://github.com/user-attachments/assets/97172792-6c7b-4088-920e-74e61bf9d87a)

**Comment by mgubaidullin** [comment]
It would help a lot to understand what you a re doing if you share YAML and application.properties

**Comment by samar-elsayed** [comment]
@mgubaidullin HYG

**Yaml file** 
```
- rest:
    id: rest-c531
    path: org/v1
    consumes: application/json
    produces: application/json
    bindingMode: auto
    post:
      - id: post-f13f
        disabled: false
        path: inquiry
        to: direct:Inquiry
        consumes: application/json
        produces: application/json
        bindingMode: "off"
        routeId: inquiry
      - id: post-bd88
        path: payment
        to: direct:Payment
        consumes: application/json
        produces: application/json
        bindingMode: "off"
        clientRequestValidation: false
- route:
    id: Inquiry
    nodePrefixId: route-94b
    from:
      id: from-18a6
      uri: direct
      parameters:
        name: Inquiry
        bridgeErrorHandler: false
      steps:
        - to:
            id: to-c6e9
            description: org Validation
            uri: kamelet:orgValidation
            parameters:
              requestType: InquiryReqBody
        - step:
            id: Inquiry Steps
            description: Inquiry Steps
            steps:
              - log:
                  id: log-389f
                  message: >-
                    Inquiry Req body from BE is
                    ${exchangeProperty.InquiryReqBody}
              - process:
                  id: process-3b07
                  description: InquiryReq
                  ref: InquiryReq
              - log:
                  id: log-67eb
                  message: Inquiry Req to SP is  === ${body}
              - to:
                  id: to-5126
                  description: SP Inquiry API
                  uri: https
                  parameters:
                    httpMethod: POST
                    skipRequestHeaders: false
                    httpUri: "{{org.inquiry.test}}"
                    bridgeEndpoint: false
              - log:
                  id: log-4fb9
                  message: Inquiry Res from SP is === ${body}
              - process:
                  id: process-36b9
                  description: InquiryRes
                  ref: InquiryRes
              - log:
                  id: log-2503
                  disabled: false
                  message: Inquiry Res to BE === ${body}
- route:
    id: Payment
    nodePrefixId: route-94b
    from:
      id: from-661f
      uri: direct
      parameters:
        name: Payment
      steps:
        - to:
            id: to-f301
            description: org Validation
            uri: kamelet:orgValidation
            parameters:
              requestType: PaymentReqBody
        - step:
            id: Payment Steps
            description: Payment Steps
            steps:
              - log:
                  id: log-ac71
                  message: Payment Req body from BE is === ${body}
              - process:
                  id: process-3b07
                  description: PaymentReq
                  ref: PaymentReq
              - log:
                  id: log-67eb
                  message: Payment Req to SP ===  ${body}
              - to:
                  id: to-5126
                  description: SP Payment API
                  uri: https
                  parameters:
                    bridgeEndpoint: false
                    httpMethod: POST
                    httpUri: "{{org.payment.test}}"
              - log:
                  id: log-4fb9
                  message: Payment Res from SP === ${body}
              - process:
                  id: process-36b9
                  description: PaymentRes
                  ref: PaymentRes
              - log:
                  id: log-2503
                  disabled: false
                  message: Payment Res to BE === ${body}

```
**application.properties**
```
camel.karavan.project-id=org-v2
camel.karavan.project-name=org-v2
camel.karavan.project-description=org-v2
camel.karavan.target=kubernetes
camel.jbang.gav=org.demo:org-v2:1
camel.jbang.version=4.5.0
camel.jbang.runtime=camel-main
# dependencies
camel.jbang.dependencies=camel-console,camel-platform-http-main,mvn:org.json:json:20231013,mvn:com.networknt:json-schema-validator:1.5.0,mvn:com.fasterxml.jackson.core:jackson-databind:2.17.2
camel.jbang.exportDir=export
camel.health.enabled=true
camel.health.exposure-level=full
camel.server.enabled=true
camel.server.healthCheckEnabled=true
camel.server.devConsoleEnabled=true
camel.main.tracingStandby=true
camel.context.dev-console=true
# Needed APIs
keycloak.host=10.90.7.82:30788/realms/master/protocol/openid-connect/token/introspect
org.inquiry.test=clientapp.org.com/api/AhlyPayments/GetInquiryPayment
org.payment.test=clientapp.org.com/api/AhlyPayments/SetPaymentAmount
# SP Credentials
apikey=5tSa6ryt2nDgrY+b+cZGyA==
###
camel.main.routesIncludePattern=file\:org_Validation/ReqBodyJsonSchemaCheck.java,file\:org_Validation/orgTokenRes.java,file\:org_Validation/orgTokenReq.java,file\:InquiryReq.java,file\:InquiryRes.java,file\:org.camel.yaml,file\:PaymentReq.java,file\:PaymentRes.java
camel.jbang.classpathFiles=file\:org_Validation/InquiryReqBody.json,file\:org_Validation/PaymentReqBody.json
camel.component.kamelet.location=classpath\:/kamelets,github\:apache\:camel-kamelets/kamelets,file\:org_Validation/orgValidation.kamelet.yaml
```
