### ISSUE TITLE
Permission issue with builder pod from Karavan on Kubernetes

### ISSUE THREAD

**Issue by tannextan** [apache/camel-karavan#1385]
### Describe the bug

[A bug happened!](error: could not lock config file //.gitconfig: Permission denied)

and 

[ERROR] Could not create local repository at /.m2/repository 

It seems that when build button is pressed , the new pod "hello-world-builder" pod generates and it uses build.sh , during build the above error encounters. 

I am using devmode-4.7.1 and came-karavan:4.7.1

This is serious and i am stuck badly on it. 
Please give some tips or solutions

Regards

### Steps to reproduce the behavior

1. Go to '...'a

### Variant

Web Application

### Container Management (if applicable)

Openshift

### Operating System (if applicable)

None

### Version

4.7.0

### Relevant log output

```shell
error: could not lock config file //.gitconfig: Permission denied
Cloning into '/karavan/code'...
The runtime option must be specified
[ERROR] Could not create local repository at /.m2/repository -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/LocalRepositoryNotAccessibleException
```

**Comment by tannextan** [comment]
This is my builder.pod.jkube.yaml

spec:
  containers:
    - env:
        - name: PROJECT_ID
          value: ${projectId}
        - name: TAG
          value: ${tag}
        - name: IMAGE_REGISTRY
          valueFrom:
            secretKeyRef:
              name: karavan
              key: karavan.container-image.registry
        - name: IMAGE_REGISTRY_USERNAME
          valueFrom:
            secretKeyRef:
              name: karavan
              key: karavan.container-image.registry-username
        - name: IMAGE_REGISTRY_PASSWORD
          valueFrom:
            secretKeyRef:
              name: karavan
              key: karavan.container-image.registry-password
        - name: IMAGE_GROUP
          valueFrom:
            secretKeyRef:
              name: karavan
              key: karavan.container-image.group
        - name: GIT_REPOSITORY
          valueFrom:
            secretKeyRef:
              name: karavan
              key: karavan.git.repository
        - name: GIT_USERNAME
          valueFrom:
            secretKeyRef:
              name: karavan
              key: karavan.git.username
        - name: GIT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: karavan
              key: karavan.git.password
        - name: GIT_BRANCH
          valueFrom:
            secretKeyRef:
              name: karavan
              key: karavan.git.branch
      securityContext:
        privileged: true
        
 Still this doesnot change the pod security level.

Please need help.

**Comment by tannextan** [comment]
Please provide any information

**Comment by tannextan** [comment]
i am trying in the deployment 4.7.0 , now this the case :

2024-08-30 09:41:12,470 INFO [org.apa.cam.kar.ser.GitService] (main) Set UsernamePasswordCredentialsProvider
2024-08-30 09:41:15,725 INFO [org.apa.cam.kar.ser.GitService] (main) Error connecting git: http://gitea:3000/karavan/karavan.git: cannot open git-upload-pack
2024-08-30 09:41:15,725 INFO [org.apa.cam.kar.KaravanStartupLoader] (main) Starting Project service: git is ready
2024-08-30 09:41:15,725 INFO [org.apa.cam.kar.ser.GitService] (main) Check git
2024-08-30 09:41:15,726 INFO [org.apa.cam.kar.ser.GitService] (main) Set UsernamePasswordCredentialsProvider
2024-08-30 09:41:15,736 INFO [org.apa.cam.kar.ser.GitService] (main) Error connecting git: http://gitea:3000/karavan/karavan.git: cannot open git-upload-pack
2024-08-30 09:41:15,736 INFO [org.apa.cam.kar.KaravanStartupLoader] (main) Import projects from git: http://gitea:3000/karavan/karavan.git


Even though i provide hardocded  value in deployment , it's taking only gitea ... 

Why ?

**Comment by mgubaidullin** [comment]
Check if env variables are in uppercase in deployment.yaml

```
        - name: "KARAVAN_GIT_REPOSITORY"
          valueFrom:
            secretKeyRef:
              key: "karavan.git.repository"
              name: "karavan"
        - name: "KARAVAN_GIT_USERNAME"
          valueFrom:
            secretKeyRef:
              key: "karavan.git.username"
              name: "karavan"
        - name: "KARAVAN_GIT_PASSWORD"
          valueFrom:
            secretKeyRef:
              key: "karavan.git.password"
              name: "karavan"
        - name: "KARAVAN_GIT_BRANCH"
          valueFrom:
            secretKeyRef:
              key: "karavan.git.branch"
              name: "karavan"
```
