### ISSUE TITLE
[VS Code] Log expression converted to char sequence

### ISSUE THREAD

**Issue by tadayosi** [apache/camel-karavan#141]
I have a yaml route like this:
```yaml
- from:
    uri: 'kamelet:wttrin-source'
    steps:
      - log: '${body}'
    parameters:
      period: '60000'
      wttrLocation: ~Eiffel+tower
      wttrLanguage: ja
```
As soo as I view it with Camel Karavan Designer on VS Code the `log` expression part is converted to a char sequence as follows:
```yaml
- from:
    uri: 'kamelet:wttrin-source'
    steps:
      - log:
          '0': $
          '1': '{'
          '2': b
          '3': o
          '4': d
          '5': 'y'
          '6': '}'
    parameters:
      period: '60000'
      wttrLocation: ~Eiffel+tower
      wttrLanguage: ja
```
