### ISSUE TITLE
karavan 4.8.1 have a bug?

### ISSUE THREAD

**Issue by nturri1306** [apache/camel-karavan#1440]
### Describe the bug

```
[jbang] Resolving dependencies...
[jbang]    org.apache.camel:camel-bom:4.8.1@pom
[jbang]    org.apache.camel:camel-jbang-core:4.8.1
[jbang]    org.apache.camel.kamelets:camel-kamelets:4.8.0
[jbang] [ERROR] Could not resolve dependencies: The following artifacts could not be resolved: org.apache.camel:camel-jbang-core:jar:4.8.1 (absent): Could not find artifact org.apache.camel:camel-jbang-core:jar:4.8.1 in central (https://repo1.maven.org/maven2)
[jbang] Run with --verbose for more details

```

```
- route:
    id: route-b026
    nodePrefixId: route-f41
    from:
      id: from-a53c
      uri: mllp
      parameters:
        hostname: 0.0.0.0
        port: "7081"
      steps:
        - log:
            id: log-f623
            message: ${body}
        - setBody:
            id: setBody-562d
            expression:
              constant:
                id: constant-e52f
                expression: ok
```

```
camel.karavan.projectId=test123
camel.karavan.projectName=test123
camel.jbang.gav=org.camel.karavan.demo:test123:1
camel.jbang.runtime=camel-main
camel.jbang.version=4.8.1
camel.jbang.dependencies=camel-console,camel-platform-http-main
camel.jbang.jib-maven-plugin-version=3.4.3
camel.server.enabled=true
camel.server.healthCheckEnabled=true
camel.server.devConsoleEnabled=true
camel.main.name=test123
camel.main.tracingStandby=true
camel.trace.enabled=true
camel.main.autoConfigurationFailFast=false
camel.routecontroller.superviseEnabled=true
camel.routecontroller.backoffDelay=5000
camel.routecontroller.backoffMaxAttempts=100
camel.routecontroller.initialDelay=1000
camel.routecontroller.threadPoolSize=3
camel.context.dev-console=true
camel.health.enabled=true
camel.health.exposure-level=full
jkube.version=1.17.0
jib.from.image=gcr.io/distroless/java17@sha256:68e2373f7bef9486c08356bd9ffd3b40b56e6b9316c5f6885eb58b1d9093b43d
```

### Steps to reproduce the behavior

1. Go to '...'a

### Variant

Web Application

### Container Management (if applicable)

None

### Operating System (if applicable)

None

### Version

4.8.1

**Comment by oscerd** [comment]
Camel 4.8.1 has not been released yet. So this is expected.

**Comment by nturri1306** [comment]
```
name: karavan

services:

  karavan:
    container_name: karavan
    image: ghcr.io/apache/camel-karavan:4.8.1
    ports:
      - "8080:8080"
    environment:
      - KARAVAN_GIT_REPOSITORY=${KARAVAN_GIT_REPOSITORY}
      - KARAVAN_GIT_USERNAME=${KARAVAN_GIT_USERNAME}
      - KARAVAN_GIT_PASSWORD=${KARAVAN_GIT_PASSWORD}
      - KARAVAN_GIT_BRANCH=main
      - KARAVAN_CONTAINER_IMAGE_REGISTRY=registry:5000
      - KARAVAN_CONTAINER_IMAGE_REGISTRY_USERNAME=
      - KARAVAN_CONTAINER_IMAGE_REGISTRY_PASSWORD=
      - KARAVAN_CONTAINER_IMAGE_GROUP=karavan
      - KARAVAN_DOCKER_NETWORK=karavan
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"    
    labels:
      - "org.apache.camel.karavan/type=internal"    
    networks:
      - karavan

  registry:
    container_name: registry
    image: registry:2
    restart: always
    ports:
      - "5555:5000"
    labels:
      - "org.apache.camel.karavan/type=internal"  
    networks:
      - karavan  

networks:
  karavan:
    name: karavan
```
