### ISSUE TITLE
Micrometer Tags are not captured from Karavan

### ISSUE THREAD

**Issue by cdia8890** [apache/camel-karavan#1520]
### Describe the bug

When using Micrometer component, the tags are not passed from the YAML to the Micrometer Component Endpoint.

Debugging the Micrometer Component

![Image](https://github.com/user-attachments/assets/cba3222a-4edf-4623-b628-449c9e1780ae)

![Image](https://github.com/user-attachments/assets/bd823074-2ff2-4a0b-8e30-7de7ede336d4)

`tags` are captured from `Map<String, Object> parameters`, but it seems tags are defined as path parameters in apache/camel-karavan/karavan-app/src/main/resources/metadata/components.json
```
"tags":{"index":2,"kind":"path","displayName":"Tags","group":"producer","label":"","required":false,"type":"object","javaType":"java.lang.Iterable<io.micrometer.core.instrument.Tag>","deprecated":false,"autowired":false,"secret":false,"description":"Tags of metrics"}
```

Highly appreciate your support in getting this resolved.

Thank you!

### Steps to reproduce the behavior

Example:

![Image](https://github.com/user-attachments/assets/91f3528d-c1be-4d18-ab6c-fe335a88210e)

Sample YAML content:
```
        - to:
            id: to-1bb1
            uri: micrometer
            parameters:
              metricsType: counter
              metricsName: eu_enterprise_services.kafka.consumer.records_processed
              increment: "1"
              tags: testKey=testValue
```

### Variant

Vs Code Extension

### Container Management (if applicable)

None

### Operating System (if applicable)

Windows

### Version

4.10.2

### Relevant log output

```shell

```
