### ISSUE TITLE
route element on CRD cause issues when running a integration

### ISSUE THREAD

**Issue by mikeintoch** [apache/camel-karavan#197]
The new version of karavan create a CRD using route element like this:

```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: hello-world.yaml
spec:
  flows:
    - route:
        from:
          uri: timer:foo
          steps:
            - setBody:
                expression:
                  constant:
                    expression: Hello World
            - log:
                message: ${body}
                logName: demo
          parameters:
            delay: '30000'

```
And when create the Integration using 'kubectl create -f integration.yaml' shows the next message
**java.lang.IllegalArgumentException: Unsupported field: steps**

Nevertheless when  use a CRD without route element definition everything runs well
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: hello-world.yaml
spec:
  flows:
    - from:
        uri: timer:foo
        steps:
          - set-body:
              expression:
                constant: Hello World
          - log:
              log-name: demo
              message: '${body}'
        parameters:
          delay: '2000'
  dependencies:
    - 'camel:timer'
```

I'm using Camel K 1.8 and k3d

Regards
