### ISSUE TITLE
Unsupported Field: steps and other errors

### ISSUE THREAD

**Issue by k0pper** [apache/camel-karavan#198]
Im trying to run this basic route: 
```
- route:
    from:
      uri: timer:foo
      steps:
        - log:
            message: Hello
      parameters:
        delay: '1200'
```

* Running it with `jbang -Dcamel.jbang.version=3.15.0 camel@apache/camel run test-integration.yaml --max-messages=10 --logging-level=info --reload ` I get the error:
```
[jbang] [ERROR] No alias found with name 'camel'
```

* Running with `jbang -Dcamel.jbang.version=3.15.0 CamelJBang@apache/camel run test-integration.yaml` I get
```
java.lang.IllegalArgumentException: Unsupported field: steps
        at org.apache.camel.dsl.yaml.common.YamlSupport.creteEndpointUri(YamlSupport.java:248) 
(...)
```

* Running with `kamel run test-integration.yaml` the POD in camel-k gets created but also throws the exception of the command before.

**Versions**
* JBang 0.83.1
* Camel-K 1.8.0
* kamel-cli 1.8.0

Am I doing something wrong? 

Alex
