### ISSUE TITLE
How do you handle the multi-level properties of a Bean?

### ISSUE THREAD

**Issue by lxf-sinksky** [apache/camel-karavan#349]
I want to add a Bean of AtomikosDataSourceBean.

```yaml
- beans: 
    - name: mysqlcloud
      type: org.springframework.boot.jta.atomikos.AtomikosDataSourceBean
      properties:
        xaDataSourceClassName: com.mysql.cj.jdbc.MysqlXADataSource
        xaProperties: 
          url: jdbc:mysql://localhost:3006/demo
          pinGlobalTxToPhysicalConnection: true
          user: username
          password: 'password'
```

But the xaProperties have subproperties.

I tried to write it in a property, but it seems to resolve to a string.
Is there a way to deal with this problem?
