### ISSUE TITLE
Custom Bean creation

### ISSUE THREAD

**Issue by Jasmin-Sk** [apache/camel-karavan#364]
I have a custom bean. I have a jar created out of custom bean. Whether we have options to load a custom bean to apache karavan?

**Comment by mgubaidullin** [comment]
you bean should be in mvn repository and then add it to your integration

<img width="1022" alt="Screen Shot 2022-06-14 at 10 56 09 AM" src="https://user-images.githubusercontent.com/1379213/173609392-fb9ac6f0-1de7-48bf-8114-f8811c99acf2.png">

**Comment by Jasmin-Sk** [comment]
I have added the custom code into the project and annotated it, but its saying "The bean name must be set must be specified". So after adding the code should I need to compile or run the code? 
--> Other than the java file in karavan-demo where else should I need to add the bean?
--> How to use the bean in components and in which components we can use this custom bean?

**Comment by mgubaidullin** [comment]
```
...
            - to:
                uri: salesforce:updateSObject
                parameters:
                  sObjectName: Opportunity
                description: Update Opportunity Object
....
    - beans:
        - name: salesforce
          type: '#class:org.apache.camel.component.salesforce.SalesforceComponent'
          properties:
            loginUrl: https://login.salesforce.com
            clientSecret: SECRET
            userName: USERNAME
            clientId: CLIENT_ID
            password: PASSWORD
```
