### ISSUE TITLE
BUG: When using the visual designer, it often inserts one or more empty array elements to the route list

### ISSUE THREAD

**Issue by InfoSec812** [apache/camel-karavan#394]
I find that the visual designer often inserts one (and sometimes more) empty array elements at the top of the route YAML:

Example:
```
# camel-k: dependency=mvn:org.apache.camel:camel-snakeyaml:3.17.0
- 
- route:
    from:
      uri: timer:periodic
```

It seems to only happen **AFTER** I have added dependencies to the file.
