### ISSUE TITLE
[VS Code] Message "File is not Camel-K Integration!" can be erroenous

### ISSUE THREAD

**Issue by apupier** [apache/camel-karavan#41]
in case of minimal Camel K files, the message is displayed. the message shoudl be more precise and mention that it is not a (?) Kubernetes Camel K file?

fo risntance with file https://github.com/apache/camel-k/blob/main/examples/languages/routes.yaml :

```
- from:
    uri: "timer:tick"
    parameters:
      period: "5000"
    steps:
      - set-body:
          constant: "Hello Yaml !!!"
      - transform:
          simple: "${body.toUpperCase()}"
      - to: "log:info"
```
Right-click and click "Karavan: Open in Designer"
