### ISSUE TITLE
SetBody EIP has 2 id options in the panel

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#454]
```
# camel-k: language=yaml

# Write your routes here, for example:
- from:
    uri: "timer:yaml"
    parameters:
      period: "1000"
    steps:
      - setBody:
          constant: "Hello {{myName}} from yaml"
      - log: "${body}"
```

Then Karavan displays 2 x ID when you select setBody (3.18.0 release)
<img width="1825" alt="Screenshot 2022-08-12 at 06 56 44" src="https://user-images.githubusercontent.com/477100/184287668-d1047215-42ea-4b00-beb3-f77c8448043f.png">
