### ISSUE TITLE
The Poll Enrich method is not working

### ISSUE THREAD

**Issue by Asraf-Uddin-Ahmed** [apache/camel-karavan#477]
This is my flow for fetching content through the **pollEnrich**.

```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: testflow
spec:
  flows:
    - route:
        from:
          uri: timer:test
          steps:
            - setBody:
                expression:
                  constant:
                    expression: Sample message
            - log:
                message: ${body}
            - pollEnrich:
                expression:
                  simple:
                    expression: file:file_src?noop=true
            - log:
                message: 'polled: ${body}'
          parameters:
            delay: '1000'
            period: '3000'
```
![image](https://user-images.githubusercontent.com/2766663/190999943-d11856f1-2337-4be3-b590-34683b53e99d.png)

My Java code is working fine. But, I am not getting any polled data here from **pollEnrich**.

**Java Version: 11
Camel Version: 3.18.1
Karavan Version: 3.18.2**

**Run command:** `jbang -Dcamel.jbang.version=3.18.1 camel@apache/camel run testflow.yaml --max-messages=10`

Please help.
