### ISSUE TITLE
Process of AggregationStrategy implementation of pollEnrich

### ISSUE THREAD

**Issue by Asraf-Uddin-Ahmed** [apache/camel-karavan#479]
After calling `pollEnrich`, I want to set a new header from the field of the previous body via `oldExchange`. But, I can't implement it. I tried [this approach](https://github.com/apache/camel-karavan/blob/main/karavan-demo/postman/project/CustomProcessor.java) but failed. Can anyone guide me to implement `AggregationStrategy` in Karavan?
 
This is my flow in Karavan:
```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: testflow
spec:
  flows:
    - route:
        from:
          uri: timer:test
          steps:
            - setBody:
                expression:
                  constant:
                    expression: Sample message
            - log:
                message: ${body}
            - pollEnrich:
                expression:
                  simple:
                    expression: file:file_src?noop=true
            - log:
                message: 'polled: ${body}'
          parameters:
            delay: '1000'
            period: '3000'
```

I want to implement this Java part of AggregationStrategy through Karavan.
```java
.....
.pollEnrich()
.simple("file:file_src?noop=true")
.timeout(0)
.cacheSize(-1)
.aggregationStrategy((oldExchange, newExchange) -> {
    newExchange.getMessage().setHeader("toEmail", oldExchange.getMessage().getBody(Map.class).get("email"));
    return newExchange;
})
.....                
```

**Java Version: 11
Camel Version: 3.18.1
Karavan Version: 3.18.2**

**Run command:** `jbang -Dcamel.jbang.version=3.18.1 camel@apache/camel run testflow.yaml`

Please help.
