### ISSUE TITLE
Fixed Namespace karavan

### ISSUE THREAD

**Issue by michael-salzburg** [apache/camel-karavan#482]
Hi all,

i have tried to setup karavan for the first time in our openshift environmet.
My available namespace differ from "karavan".

On karavan-app startup the application tries to access the "karavan" namespace which is not allowed for the current service-user

It this namespace "karavan" fixed or can i configure somehow a different name.

Thanks
 Michael

**Comment by mgubaidullin** [comment]
Karavan should work in another namespace. If not it is a bug.

1. Set correct namespace in all manifests in `karavan-cloud` folder
2. Overwrite environment namespace defined in `application.properties' 
```
...
karavan.config.environments[0].namespace=karavan
...
```
in your karavan deployment manifest by adding environment variable
```
            - name: KARAVAN_CONFIG_ENVIRONMENTS_0__NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: your_namespace
```
