### ISSUE TITLE
Include // camel-k header to allow camel-k tooling assistance

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#495]
Lets include in the top comment as below

    # camel-k: language=yaml

```
❯ camel init bar.yaml
❯ cat bar.yaml
# camel-k: language=yaml

# Write your routes here, for example:
- from:
    uri: "timer:yaml"
    parameters:
      period: "1000"
    steps:
      - setBody:
          constant: "Hello Camel from yaml"
      - log: "${body}"
```

As this allows tooling assistance for camel-k textual tool
