### ISSUE TITLE
Using resilienc4j as circuit breaker - error in generated yaml

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#506]
```
- route:
    from:
      uri: timer:yaml
      steps:
        - setBody:
            expression:
              constant:
                expression: Hello Camel from yaml
        - circuitBreaker:
            steps:
              - throwException:
                  message: Forced error
                  exceptionType: java.lang.IllegalArgument
            resilience4jConfiguration:
              resilience4jConfiguration:
                minimumNumberOfCalls: 5
                failureRateThreshold: 50
        - log:
            message: ${body}
      parameters:
        period: '1000'
```

**Comment by davsclaus** [comment]
It seems that this 
```
            resilience4jConfiguration:
              resilience4jConfiguration:
```

Should just be once, eg

```
            resilience4jConfiguration:
```

**Comment by davsclaus** [comment]
Unsupported field: resilience4jConfiguration
 in file:mycb.yaml, line 16, column 17:
                    minimumNumberOfCalls: 5
                    ^

	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.handleUnknownProperty(YamlDeserializerBase.java:132)
	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.setProperties(YamlDeserializerBase.java:126)
	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:65)
	at org.apache.camel.dsl.yaml.common.YamlDeserializationContext$1.construct(YamlDeserializationContext.java:171)
	at org.apache.camel.dsl.yaml.common.YamlDeserializerSupport.asType(YamlDeserializerSupport.java:332)
	at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$CircuitBreakerDefinitionDeserializer.setProperty(ModelDeserializers.java:1735)
	at org.apache.camel.dsl.yaml.deserializers.ModelDeserializers$CircuitBreakerDefinitionDeserializer.setProperty(ModelDeserializers.java:1676)
	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.setProperties(YamlDeserializerBase.java:125)
	at org.apache.camel.dsl.yaml.common.YamlDeserializerBase.construct(YamlDeserializerBase.java:65)

**Comment by davsclaus** [comment]
Here is a working example

```
- route:
    from:
      uri: timer:yaml
      steps:
        - setBody:
            expression:
              constant:
                expression: Hello Camel from yaml
        - circuitBreaker:
            steps:
              - throwException:
                  message: Forced error
                  exceptionType: java.lang.IllegalArgumentException
            resilience4jConfiguration:
              minimumNumberOfCalls: 10
              failureRateThreshold: 50
        - log:
            message: ${body}
      parameters:
        period: '1000'
```

**Comment by davsclaus** [comment]
Its the same for MP fault tolerance
```
        - circuitBreaker:
            steps:
              - throwException:
                  message: Forced error
                  exceptionType: java.lang.IllegalArgumentException
            faultToleranceConfiguration:
              faultToleranceConfiguration:
                successThreshold: 10
```

There are 2 x configuration
