### ISSUE TITLE
All the steps locks

### ISSUE THREAD

**Issue by mrinalsharma** [apache/camel-karavan#556]
With the latest code, all the route steps lock after moving out of the designer view and then coming back to the designer view.
![image](https://user-images.githubusercontent.com/3838113/207097807-dfa822c0-e4ca-4ffb-a6fd-d62a640c0139.png)

The generated .yaml definition looks like
```
- dslName: RouteDefinition
  stepName: route
  from:
    uri: 'quartz:foo?cron={{myCron}}'
    steps:
      - uri: 'bean:myBean?method=hello'
        dslName: ToDefinition
        stepName: to
        inArray: true
        inSteps: true
      - dslName: LogDefinition
        stepName: log
        message: '${body}'
        inArray: true
        inSteps: true
      - uri: 'bean:myBean?method=bye'
        dslName: ToDefinition
        stepName: to
        inArray: true
        inSteps: true
      - dslName: LogDefinition
        stepName: log
        message: '${body}'
        inArray: true
        inSteps: true
      - dslName: LoopDefinition
        stepName: loop
        expression:
          dslName: ExpressionDefinition
          stepName: expression
        inArray: true
        inSteps: true
    dslName: FromDefinition
    stepName: from
  id: foo
```

**Comment by mrinalsharma** [comment]
This is in karavan-app

**Comment by mrinalsharma** [comment]
are you able to reproduce this issue?

**Comment by mgubaidullin** [comment]
nope. could you please try to install the latest karavan-core

**Comment by mrinalsharma** [comment]
> nope. could you please try to install the latest karavan-core

Sure I will try to install it again.

**Comment by mrinalsharma** [comment]
I just tried again pulling latest code.
![image](https://user-images.githubusercontent.com/3838113/207434716-7407788b-2468-471b-935c-ea600a3f89f9.png)

Generated yaml
```
- dslName: RouteDefinition
  stepName: route
  from:
    uri: 'kamelet:aws-redshift-source'
    steps:
      - dslName: LogDefinition
        stepName: log
        inArray: true
        inSteps: true
    dslName: FromDefinition
    stepName: from

```

**Comment by mrinalsharma** [comment]
@mgubaidullin  The issue still exists, I just tested with latest ghcr.io/apache/camel-karavan:3.18.6 and can see the issue.

yaml looks like 
```
- dslName: RouteDefinition
  stepName: route
  from:
    dslName: FromDefinition
    stepName: from
    uri: 'kamelet:timer-source'
    parameters:
      message: Hello World
    steps:
      - dslName: LogDefinition
        stepName: log
        message: '${body}'
        inArray: true
        inSteps: true

```
![image](https://user-images.githubusercontent.com/3838113/208983608-99f5fd95-36e6-476c-a2f7-69c511b82522.png)
