### ISSUE TITLE
karavan.space - White page with custom yaml

### ISSUE THREAD

**Issue by Croway** [apache/camel-karavan#652]
Using the following yaml

```
- route:
    from:
      uri: "file:foo"
      steps:
        -to:
          uri: "jms:queue:foo"
```

in the code tab and the switch to the Design tab, an empty page is shown with the following error:

```
react-dom.production.min.js:216 TypeError: t.forEach is not a function
    at e.readSteps (CamelDefinitionYamlStep.js:4546:22)

CamelDefinitionYamlStep.js:4546 Uncaught TypeError: t.forEach is not a function
    at e.readSteps (CamelDefinitionYamlStep.js:4546:22)
```
