### ISSUE TITLE
Need ability to provide xpression for xtokenize 

### ISSUE THREAD

**Issue by chiragsanghavi** [apache/camel-karavan#684]
Following is a valid route as per 3.20.3 (not releated yet) and 4.0.0-M2.
```
- route:
    id: route-a6b4
    from:
      uri: file:/home/myfolder/batchsplit/in
      id: from-d1ca
      steps:
        - split:
            id: split-6d45
            expression:
              xtokenize:
                id: xtokenize-dca2
                mode: w
                expression: //BatchMaster
            streaming: true
            steps:
              - to:
                  uri: file:/home/myfolder/batchsplit/out?fileName=${exchangeId}.xml
                  id: to-1a10
```

While creating / viewing this in Karavan; it does not allow editing or creating expression of ```//BatchMaster```.
