### ISSUE TITLE
VS Code: Designer removes "intercept" section from YAML

### ISSUE THREAD

**Issue by mikoskinen** [apache/camel-karavan#787]
The VS Code designer doesn't seem to yet have support for intercept. The main problem is that if intercept is manually added to the yaml-file, the designer completely removes it.

Steps to reproduce:
1. Create route using designer
2. Add intercept into the top of the yaml-file and save file
3. Re-open the designer
4. Make a change using the designer
5. Notice how intercept is gone from the yaml-file

**Comment by mikoskinen** [comment]
But! It seems the designer has a support for adding intercept using route configuration! That is great, and perfect workaround in my situation. 

So maybe close this, what do you think?

**Comment by mikoskinen** [comment]
Manually editing the YAML to this seems to have worked:

```
- routeConfiguration:
    intercept:
      - id: intercept-6d50
        intercept:
          id: intercept-233
          steps:
            - log:
                message: 'Intercepted: ${body}'
```
The designer doesn't render it but the good thing is that the designer doesn't seem to be deleting anything.
