### ISSUE TITLE
Add the option to save/export only the routes and not the integration for standalone

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-karavan#79]
Add an option to export the yaml flow without the surrounding metadata related to the integration.

Instead of 

```
apiVersion: camel.apache.org/v1
kind: Integration
metadata:
  name: integration1
spec:
  flows:
    - from:
        parameters:
          period: 3000
        steps:
          - log:
              logName: result
              loggingLevel: INFO
              message: '${body}'
        uri: 'kamelet:chuck-norris-source'
```

just this:

```
# camel-k: language=yaml

- from:
    uri: 'kamelet:chuck-norris-source'
    parameters:
      period: 3000
    steps:
      - to: "log:info"```
