### ISSUE TITLE
Karavan Space - Should parse URIs with only parameters

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#800]
This yaml should be possible to copy into code tab in karavan space, and then flip to design view

```
- route:
    id: myRoute
    from:
      uri: seda
      parameters:
        name: foo
        size: 1234
        multipleConsumers: true
      steps:
        - transform:
            id: transform
            simple:
              expression: "Hello ${body}"
        - to:
            id: myMock
            uri: mock
            parameters:
              name: result
              retainFirst: 5
              failFast: true
```
