### ISSUE TITLE
[VS Code] Parameters not added to uri

### ISSUE THREAD

**Issue by hguerrero** [apache/camel-karavan#840]
When using the latest version of Karavan, standard path parameters like name in the `direct` component are handled as *query parameters* and not added to the `uri`.

Example:
```yaml
- route:
    id: route-bb42
    from:
      uri: direct
      id: from-1cbc
      parameters:
        name: order
...
```

Expected:
```yaml
- route:
    id: route-bb42
    from:
      id: from-6530
      uri: direct:order
```

Same happens with other components like `jms`

**Comment by mgubaidullin** [comment]
Path Parameters Update: Starting from version 3.21.0, Karavan sets path parameters in the same way as query parameters (key: value). This change enhances consistency in the handling of parameters and simplifies the overall DSL design.
```
- route:
    from:
      uri: activemq
      parameters:
        destinationType: topic
        destinationName: topic1

```
