### ISSUE TITLE
kamelet is internal only

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#854]
Paste the following into karavan space

```
- route:
    id: route1
    from:
      uri: kamelet:beer-source
      steps:
        - removeHeaders:
            id: removeHeaders1
            pattern: '*'
        - to:
            id: to1
            uri: activemq:beer


- route:
    id: route2
    from:
      uri: activemq:beer
      steps:
        - log:
            id: log1
            message: "${body}"


- route:
    id: beer-source-1
    template: "true"
    from:
      uri: timer:beer?period=5000
      steps:
        - to:
            id: to2
            uri: https://random-data-api.com/api/beer/random_beer
        - to:
            id: to3
            uri: kamelet://sink?routeId=beer-source-1
```

And notice how the UI shows the last kamelet is external
<img width="1855" alt="Screenshot 2023-08-10 at 11 26 42" src="https://github.com/apache/camel-karavan/assets/477100/c57a8ad2-d146-4817-a8ab-c83a8d0bb516">
