### ISSUE TITLE
Uri for elasticsearch-rest is corrupted while editing a route on karavan

### ISSUE THREAD

**Issue by filipeabreutd** [apache/camel-karavan#869]
When editing a route on the UI, the step parameter **uri** of type _elasticsearch-rest_ is corrupted and stops working:

Example:

>    - toD:
>           uri: elasticsearch-rest://elasticsearch

changes to:

>   - toD:
>         uri: elasticsearch-rest

- Which makes the route to stop working.

**Comment by davsclaus** [comment]
the uri should be changed to key/value pairs, so there should be parameters with the value after colon.
This is correct YAML DSL and what karavan uses onwards.

**Comment by davsclaus** [comment]
But yeah toD is dynamic and karavan should leave the field as-is, as it can be `kafka:${header.blah}` etc

**Comment by davsclaus** [comment]
@mgubaidullin I think we should have this looked at and fixed for next release

**Comment by davsclaus** [comment]
```
- route:
    id: route-24d9
    from:
      uri: kamelet:aws-cloudtrail-source
      id: from-4ff7
      steps:
        - toD:
            uri: kafka:${header.foo}
            id: toD-3e75
```

If you then click in the UI then the toD uri is changed to `kafka`
