### ISSUE TITLE
Karavan Space - Bean properties does not show

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#897]
When adding a bean, with properties, then after you have added them via the UI, and click "routes" or something and then come back to "beans" then the properties table is gone.

For example this bean and route
```
- beans:
  - name: messageHistoryFactory
    type: org.apache.camel.impl.engine.DefaultMessageHistoryFactory
    properties:
      copyMessage: true

- route:
    messageHistory: true
    from:
      uri: "timer:yaml"
      parameters:
        period: "3000"
      steps:
        - to:
            uri: "log:test"
```
