### ISSUE TITLE
Karavan Designer - Properties Panel should indicate which options has been explicit configured

### ISSUE THREAD

**Issue by davsclaus** [apache/camel-karavan#921]
When working on components or EIPs that have many options, then it would be nice if the properties panel could highlight which options has been configured (eg has value in YAML).

This allows to quickly see these options, as those are often what you need to understand and maybe also update etc. Maybe the UI could have some kind of different color, or some kind of visual indentication.

An example below in the AMQP component.

Here are only 2 options set, but the UI panel has many more, and at first glance it can be hard to find out which has been set or not.

<img width="2173" alt="Screenshot 2023-10-02 at 12 52 52" src="https://github.com/apache/camel-karavan/assets/477100/97a46273-33c3-445c-a157-71b8f507f4c3">

**Comment by davsclaus** [comment]
And the YAML DSL
```
- route:
    id: amqp-producer
    from:
      uri: netty-http
      id: from-b4e7
      parameters:
        protocol: http
        host: localhost:{{netty.port}}
        path: message
      steps:
        - log:
            message: got Netty request, about to send AMQP message.
            id: log-69c1
        - to:
            uri: amqp
            id: to-5fea
            parameters:
              destinationType: queue
              destinationName: myqueue
- route:
    id: amqp-consumer
    from:
      uri: amqp
      id: from-d77e
      parameters:
        destinationType: queue
        destinationName: myqueue
      steps:
        - log:
            message: got AMQP request, about to respond.
            id: log-44b2
        - setBody:
            expression:
              simple:
                expression: Hello from Camel's AMQP example
                id: simple-05f4
            id: setBody-1796
- beans:
    - name: jmsConnectionFactory
      properties:
        remoteURI: amqp://localhost:5672
      type: org.apache.qpid.jms.JmsConnectionFactory
    - name: amqp
      properties:
        connectionFactory: '#bean:jmsConnectionFactory'
      type: org.apache.camel.component.amqp.AMQPComponent

```
